two_lulz_homepage:
    path: /
    defaults: {_controller:TwoLulzBundle:Post:index}

posts:
    type: rest
    resource: "@TwoLulzBundle/Controller/PostController.php"

comments:
    type: rest
    resource: "@TwoLulzBundle/Controller/CommentController.php"