TwoLulzBundle\Entity\Post:
   properties:
        image:
            - Image:
                notFoundMessage: Image not uploaded
                uploadErrorMessage: The image could not upload. Try again
                minWidth: 16
                maxWidthMessage: image trop courte
                maxWidth: 4000
                maxWidthMessage: image trop longue
                minHeight: 16
                minHeightMessage: image trop petite
                maxHeight: 4000
                maxHeightMessage: image trop grande
                maxSize: 200k
                maxSizeMessage: Image trop grosse
                uploadIniSizeErrorMessage: Image trop trop trop grosse
                uploadFormSizeErrorMessage: Image trop large
                notReadableMessage: Illisible