two_lulz:
    resource: "@TwoLulzBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#REST
rest :
  resource : "@TwoLulzBundle/Resources/config/routing_rest.yml"
  prefix : /api

